
name: Test Docker load
on:
  workflow_dispatch:
  push:
    paths:
      - '**/build-docker.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull
        shell: bash
        run: |
          docker pull --quiet 'ghcr.io/sebbasf/infra-pelican:latest'
      - name: Docker exec
        uses: sebbASF/infra-pelican@docker-action
