name: Build a Pelican Website
on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      # - uses: apache/infrastructure-actions/build-pelican@simplify # temp override
      - uses: sebbASF/infra-actions/build-pelican@main
        with:
          destination: 'gha-site'
          progress: false
          # Temp override
          image: 'ghcr.io/sebbasf/infra-pelican:latest'
