name: Build a Pelican Website Main
on:
  push:
    paths:
      - '**/build-pelican.yml'
  workflow_dispatch:
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: apache/infrastructure-actions/build-pelican@main
      - uses: sebbASF/my-site/asf-action@main
        with:
          destination: 'gha-site'
          gfm: 'true'
